/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import me.pagar.api.DateTimeHelper;
import org.joda.time.DateTime;

@JsonInclude(Include.ALWAYS)
public class CreateBoletoPaymentRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1173789506515223715L;
    private int retries;
    private String bank;
    private String instructions;
    private DateTime dueAt;
    private CreateAddressRequest billingAddress;
    private String billingAddressId;
    private String nossoNumero;
    private String documentNumber;
    private String statementDescriptor;
    /** GETTER
     * Number of retries
     */
    @JsonGetter("retries")
    public int getRetries ( ) { 
        return this.retries;
    }
    
    /** SETTER
     * Number of retries
     */
    @JsonSetter("retries")
    public void setRetries (int value) { 
        this.retries = value;
    }
 
    /** GETTER
     * The bank code, containing three characters. The available codes are on the API specification
     */
    @JsonGetter("bank")
    public String getBank ( ) { 
        return this.bank;
    }
    
    /** SETTER
     * The bank code, containing three characters. The available codes are on the API specification
     */
    @JsonSetter("bank")
    public void setBank (String value) { 
        this.bank = value;
    }
 
    /** GETTER
     * The instructions field that will be printed on the boleto.
     */
    @JsonGetter("instructions")
    public String getInstructions ( ) { 
        return this.instructions;
    }
    
    /** SETTER
     * The instructions field that will be printed on the boleto.
     */
    @JsonSetter("instructions")
    public void setInstructions (String value) { 
        this.instructions = value;
    }
 
    /** GETTER
     * Boleto due date
     */
    @JsonGetter("due_at")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getDueAt ( ) { 
        return this.dueAt;
    }
    
    /** SETTER
     * Boleto due date
     */
    @JsonSetter("due_at")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDueAt (DateTime value) { 
        this.dueAt = value;
    }
 
    /** GETTER
     * Card's billing address
     */
    @JsonGetter("billing_address")
    public CreateAddressRequest getBillingAddress ( ) { 
        return this.billingAddress;
    }
    
    /** SETTER
     * Card's billing address
     */
    @JsonSetter("billing_address")
    public void setBillingAddress (CreateAddressRequest value) { 
        this.billingAddress = value;
    }
 
    /** GETTER
     * The address id for the billing address
     */
    @JsonGetter("billing_address_id")
    public String getBillingAddressId ( ) { 
        return this.billingAddressId;
    }
    
    /** SETTER
     * The address id for the billing address
     */
    @JsonSetter("billing_address_id")
    public void setBillingAddressId (String value) { 
        this.billingAddressId = value;
    }
 
    /** GETTER
     * Customer identification number with the bank
     */
    @JsonGetter("nosso_numero")
    public String getNossoNumero ( ) { 
        return this.nossoNumero;
    }
    
    /** SETTER
     * Customer identification number with the bank
     */
    @JsonSetter("nosso_numero")
    public void setNossoNumero (String value) { 
        this.nossoNumero = value;
    }
 
    /** GETTER
     * Boleto identification
     */
    @JsonGetter("document_number")
    public String getDocumentNumber ( ) { 
        return this.documentNumber;
    }
    
    /** SETTER
     * Boleto identification
     */
    @JsonSetter("document_number")
    public void setDocumentNumber (String value) { 
        this.documentNumber = value;
    }
 
    /** GETTER
     * Soft Descriptor
     */
    @JsonGetter("statement_descriptor")
    public String getStatementDescriptor ( ) { 
        return this.statementDescriptor;
    }
    
    /** SETTER
     * Soft Descriptor
     */
    @JsonSetter("statement_descriptor")
    public void setStatementDescriptor (String value) { 
        this.statementDescriptor = value;
    }
 
}
