/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CreateConfirmPaymentRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8616765294039872738L;
    private String description;
    private Integer amount;
    private String code;
    /** GETTER
     * Description
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * Description
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * Amount
     */
    @JsonGetter("Amount")
    public Integer getAmount ( ) { 
        return this.amount;
    }
    
    /** SETTER
     * Amount
     */
    @JsonSetter("Amount")
    public void setAmount (Integer value) { 
        this.amount = value;
    }
 
    /** GETTER
     * Code reference
     */
    @JsonGetter("Code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * Code reference
     */
    @JsonSetter("Code")
    public void setCode (String value) { 
        this.code = value;
    }
 
}
