/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import me.pagar.api.DateTimeHelper;
import org.joda.time.DateTime;

@JsonInclude(Include.ALWAYS)
public class CreatePeriodRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -72775155535351533L;
    private DateTime endAt;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("end_at")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getEndAt ( ) { 
        return this.endAt;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("end_at")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setEndAt (DateTime value) { 
        this.endAt = value;
    }
 
}
