/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class CreateUsageRequestBuilder {
    //the instance to build
    private CreateUsageRequest createUsageRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateUsageRequestBuilder() {
        createUsageRequest = new CreateUsageRequest();
    }

    public CreateUsageRequestBuilder quantity(int quantity) {
        createUsageRequest.setQuantity(quantity);
        return this;
    }

    public CreateUsageRequestBuilder description(String description) {
        createUsageRequest.setDescription(description);
        return this;
    }

    public CreateUsageRequestBuilder usedAt(DateTime usedAt) {
        createUsageRequest.setUsedAt(usedAt);
        return this;
    }

    /**
     * Identification code in the client system
     */
    public CreateUsageRequestBuilder code(String code) {
        createUsageRequest.setCode(code);
        return this;
    }

    /**
     * identification group in the client system
     */
    public CreateUsageRequestBuilder group(String group) {
        createUsageRequest.setGroup(group);
        return this;
    }

    /**
     * Field used in item scheme type 'Percent'
     */
    public CreateUsageRequestBuilder amount(Integer amount) {
        createUsageRequest.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateUsageRequest build() {
        return createUsageRequest;
    }
}