/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CreateEmvDataTlvDecryptRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1005950601618945345L;
    private String tag;
    private String lenght;
    private String value;
    /** GETTER
     * Emv tag
     */
    @JsonGetter("tag")
    public String getTag ( ) { 
        return this.tag;
    }
    
    /** SETTER
     * Emv tag
     */
    @JsonSetter("tag")
    public void setTag (String value) { 
        this.tag = value;
    }
 
    /** GETTER
     * Emv lenght
     */
    @JsonGetter("lenght")
    public String getLenght ( ) { 
        return this.lenght;
    }
    
    /** SETTER
     * Emv lenght
     */
    @JsonSetter("lenght")
    public void setLenght (String value) { 
        this.lenght = value;
    }
 
    /** GETTER
     * Emv value
     */
    @JsonGetter("value")
    public String getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * Emv value
     */
    @JsonSetter("value")
    public void setValue (String value) { 
        this.value = value;
    }
 
}
