/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreatePlanItemRequestBuilder {
    //the instance to build
    private CreatePlanItemRequest createPlanItemRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreatePlanItemRequestBuilder() {
        createPlanItemRequest = new CreatePlanItemRequest();
    }

    /**
     * Item name
     */
    public CreatePlanItemRequestBuilder name(String name) {
        createPlanItemRequest.setName(name);
        return this;
    }

    /**
     * Item's pricing scheme
     */
    public CreatePlanItemRequestBuilder pricingScheme(CreatePricingSchemeRequest pricingScheme) {
        createPlanItemRequest.setPricingScheme(pricingScheme);
        return this;
    }

    /**
     * Item's id
     */
    public CreatePlanItemRequestBuilder id(String id) {
        createPlanItemRequest.setId(id);
        return this;
    }

    /**
     * Item's description
     */
    public CreatePlanItemRequestBuilder description(String description) {
        createPlanItemRequest.setDescription(description);
        return this;
    }

    /**
     * Number of cycles where the item will be charged
     */
    public CreatePlanItemRequestBuilder cycles(Integer cycles) {
        createPlanItemRequest.setCycles(cycles);
        return this;
    }

    /**
     * Quantity
     */
    public CreatePlanItemRequestBuilder quantity(Integer quantity) {
        createPlanItemRequest.setQuantity(quantity);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatePlanItemRequest build() {
        return createPlanItemRequest;
    }
}