/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreatePhonesRequestBuilder {
    //the instance to build
    private CreatePhonesRequest createPhonesRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreatePhonesRequestBuilder() {
        createPhonesRequest = new CreatePhonesRequest();
    }

    public CreatePhonesRequestBuilder homePhone(CreatePhoneRequest homePhone) {
        createPhonesRequest.setHomePhone(homePhone);
        return this;
    }

    public CreatePhonesRequestBuilder mobilePhone(CreatePhoneRequest mobilePhone) {
        createPhonesRequest.setMobilePhone(mobilePhone);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatePhonesRequest build() {
        return createPhonesRequest;
    }
}