/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreatePricingSchemeRequestBuilder {
    //the instance to build
    private CreatePricingSchemeRequest createPricingSchemeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreatePricingSchemeRequestBuilder() {
        createPricingSchemeRequest = new CreatePricingSchemeRequest();
    }

    /**
     * Scheme type
     */
    public CreatePricingSchemeRequestBuilder schemeType(String schemeType) {
        createPricingSchemeRequest.setSchemeType(schemeType);
        return this;
    }

    /**
     * Price brackets
     */
    public CreatePricingSchemeRequestBuilder priceBrackets(List<CreatePriceBracketRequest> priceBrackets) {
        createPricingSchemeRequest.setPriceBrackets(priceBrackets);
        return this;
    }

    /**
     * Price
     */
    public CreatePricingSchemeRequestBuilder price(Integer price) {
        createPricingSchemeRequest.setPrice(price);
        return this;
    }

    /**
     * Minimum price
     */
    public CreatePricingSchemeRequestBuilder minimumPrice(Integer minimumPrice) {
        createPricingSchemeRequest.setMinimumPrice(minimumPrice);
        return this;
    }

    /**
     * percentual value used in pricing_scheme Percent
     */
    public CreatePricingSchemeRequestBuilder percentage(Double percentage) {
        createPricingSchemeRequest.setPercentage(percentage);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatePricingSchemeRequest build() {
        return createPricingSchemeRequest;
    }
}