/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreateSellerRequestBuilder {
    //the instance to build
    private CreateSellerRequest createSellerRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateSellerRequestBuilder() {
        createSellerRequest = new CreateSellerRequest();
    }

    /**
     * Name
     */
    public CreateSellerRequestBuilder name(String name) {
        createSellerRequest.setName(name);
        return this;
    }

    /**
     * Seller's code identification
     */
    public CreateSellerRequestBuilder code(String code) {
        createSellerRequest.setCode(code);
        return this;
    }

    /**
     * Description
     */
    public CreateSellerRequestBuilder description(String description) {
        createSellerRequest.setDescription(description);
        return this;
    }

    /**
     * Document number (individual / company)
     */
    public CreateSellerRequestBuilder document(String document) {
        createSellerRequest.setDocument(document);
        return this;
    }

    /**
     * Address
     */
    public CreateSellerRequestBuilder address(CreateAddressRequest address) {
        createSellerRequest.setAddress(address);
        return this;
    }

    /**
     * Person type (individual / company)
     */
    public CreateSellerRequestBuilder type(String type) {
        createSellerRequest.setType(type);
        return this;
    }

    /**
     * Metadata
     */
    public CreateSellerRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        createSellerRequest.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateSellerRequest build() {
        return createSellerRequest;
    }
}