/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class CreateAnticipationRequestBuilder {
    //the instance to build
    private CreateAnticipationRequest createAnticipationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateAnticipationRequestBuilder() {
        createAnticipationRequest = new CreateAnticipationRequest();
    }

    /**
     * Amount requested for the anticipation
     */
    public CreateAnticipationRequestBuilder amount(int amount) {
        createAnticipationRequest.setAmount(amount);
        return this;
    }

    /**
     * Timeframe
     */
    public CreateAnticipationRequestBuilder timeframe(String timeframe) {
        createAnticipationRequest.setTimeframe(timeframe);
        return this;
    }

    /**
     * Payment date
     */
    public CreateAnticipationRequestBuilder paymentDate(DateTime paymentDate) {
        createAnticipationRequest.setPaymentDate(paymentDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateAnticipationRequest build() {
        return createAnticipationRequest;
    }
}