/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreateCheckoutBankTransferRequestBuilder {
    //the instance to build
    private CreateCheckoutBankTransferRequest createCheckoutBankTransferRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateCheckoutBankTransferRequestBuilder() {
        createCheckoutBankTransferRequest = new CreateCheckoutBankTransferRequest();
    }

    /**
     * Bank
     */
    public CreateCheckoutBankTransferRequestBuilder bank(List<String> bank) {
        createCheckoutBankTransferRequest.setBank(bank);
        return this;
    }

    /**
     * Number of retries for processing
     */
    public CreateCheckoutBankTransferRequestBuilder retries(int retries) {
        createCheckoutBankTransferRequest.setRetries(retries);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateCheckoutBankTransferRequest build() {
        return createCheckoutBankTransferRequest;
    }
}