/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CreateSplitRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -6652989674833980098L;
    private String type;
    private int amount;
    private String recipientId;
    private CreateSplitOptionsRequest options;
    /** GETTER
     * Split type
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Split type
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * Amount
     */
    @JsonGetter("amount")
    public int getAmount ( ) { 
        return this.amount;
    }
    
    /** SETTER
     * Amount
     */
    @JsonSetter("amount")
    public void setAmount (int value) { 
        this.amount = value;
    }
 
    /** GETTER
     * Recipient id
     */
    @JsonGetter("recipient_id")
    public String getRecipientId ( ) { 
        return this.recipientId;
    }
    
    /** SETTER
     * Recipient id
     */
    @JsonSetter("recipient_id")
    public void setRecipientId (String value) { 
        this.recipientId = value;
    }
 
    /** GETTER
     * The split options request
     */
    @JsonGetter("options")
    public CreateSplitOptionsRequest getOptions ( ) { 
        return this.options;
    }
    
    /** SETTER
     * The split options request
     */
    @JsonSetter("options")
    public void setOptions (CreateSplitOptionsRequest value) { 
        this.options = value;
    }
 
}
