/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreateInvoiceRequestBuilder {
    //the instance to build
    private CreateInvoiceRequest createInvoiceRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateInvoiceRequestBuilder() {
        createInvoiceRequest = new CreateInvoiceRequest();
    }

    /**
     * Metadata
     */
    public CreateInvoiceRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        createInvoiceRequest.setMetadata(metadata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateInvoiceRequest build() {
        return createInvoiceRequest;
    }
}