/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreatePaymentAuthenticationRequestBuilder {
    //the instance to build
    private CreatePaymentAuthenticationRequest createPaymentAuthenticationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreatePaymentAuthenticationRequestBuilder() {
        createPaymentAuthenticationRequest = new CreatePaymentAuthenticationRequest();
    }

    /**
     * The Authentication type
     */
    public CreatePaymentAuthenticationRequestBuilder type(String type) {
        createPaymentAuthenticationRequest.setType(type);
        return this;
    }

    /**
     * The 3D-S authentication object
     */
    public CreatePaymentAuthenticationRequestBuilder threedSecure(CreateThreeDSecureRequest threedSecure) {
        createPaymentAuthenticationRequest.setThreedSecure(threedSecure);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatePaymentAuthenticationRequest build() {
        return createPaymentAuthenticationRequest;
    }
}