/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreateBankAccountRequestBuilder {
    //the instance to build
    private CreateBankAccountRequest createBankAccountRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateBankAccountRequestBuilder() {
        createBankAccountRequest = new CreateBankAccountRequest();
    }

    /**
     * Bank account holder name
     */
    public CreateBankAccountRequestBuilder holderName(String holderName) {
        createBankAccountRequest.setHolderName(holderName);
        return this;
    }

    /**
     * Bank account holder type
     */
    public CreateBankAccountRequestBuilder holderType(String holderType) {
        createBankAccountRequest.setHolderType(holderType);
        return this;
    }

    /**
     * Bank account holder document
     */
    public CreateBankAccountRequestBuilder holderDocument(String holderDocument) {
        createBankAccountRequest.setHolderDocument(holderDocument);
        return this;
    }

    /**
     * Bank
     */
    public CreateBankAccountRequestBuilder bank(String bank) {
        createBankAccountRequest.setBank(bank);
        return this;
    }

    /**
     * Branch number
     */
    public CreateBankAccountRequestBuilder branchNumber(String branchNumber) {
        createBankAccountRequest.setBranchNumber(branchNumber);
        return this;
    }

    /**
     * Branch check digit
     */
    public CreateBankAccountRequestBuilder branchCheckDigit(String branchCheckDigit) {
        createBankAccountRequest.setBranchCheckDigit(branchCheckDigit);
        return this;
    }

    /**
     * Account number
     */
    public CreateBankAccountRequestBuilder accountNumber(String accountNumber) {
        createBankAccountRequest.setAccountNumber(accountNumber);
        return this;
    }

    /**
     * Account check digit
     */
    public CreateBankAccountRequestBuilder accountCheckDigit(String accountCheckDigit) {
        createBankAccountRequest.setAccountCheckDigit(accountCheckDigit);
        return this;
    }

    /**
     * Bank account type
     */
    public CreateBankAccountRequestBuilder type(String type) {
        createBankAccountRequest.setType(type);
        return this;
    }

    /**
     * Metadata
     */
    public CreateBankAccountRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        createBankAccountRequest.setMetadata(metadata);
        return this;
    }

    /**
     * Pix key
     */
    public CreateBankAccountRequestBuilder pixKey(String pixKey) {
        createBankAccountRequest.setPixKey(pixKey);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateBankAccountRequest build() {
        return createBankAccountRequest;
    }
}