/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetAnticipationLimitResponseBuilder {
    //the instance to build
    private GetAnticipationLimitResponse getAnticipationLimitResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetAnticipationLimitResponseBuilder() {
        getAnticipationLimitResponse = new GetAnticipationLimitResponse();
    }

    /**
     * Amount
     */
    public GetAnticipationLimitResponseBuilder amount(int amount) {
        getAnticipationLimitResponse.setAmount(amount);
        return this;
    }

    /**
     * Anticipation fee
     */
    public GetAnticipationLimitResponseBuilder anticipationFee(int anticipationFee) {
        getAnticipationLimitResponse.setAnticipationFee(anticipationFee);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetAnticipationLimitResponse build() {
        return getAnticipationLimitResponse;
    }
}