/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetBillingAddressResponseBuilder {
    //the instance to build
    private GetBillingAddressResponse getBillingAddressResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetBillingAddressResponseBuilder() {
        getBillingAddressResponse = new GetBillingAddressResponse();
    }

    public GetBillingAddressResponseBuilder street(String street) {
        getBillingAddressResponse.setStreet(street);
        return this;
    }

    public GetBillingAddressResponseBuilder number(String number) {
        getBillingAddressResponse.setNumber(number);
        return this;
    }

    public GetBillingAddressResponseBuilder zipCode(String zipCode) {
        getBillingAddressResponse.setZipCode(zipCode);
        return this;
    }

    public GetBillingAddressResponseBuilder neighborhood(String neighborhood) {
        getBillingAddressResponse.setNeighborhood(neighborhood);
        return this;
    }

    public GetBillingAddressResponseBuilder city(String city) {
        getBillingAddressResponse.setCity(city);
        return this;
    }

    public GetBillingAddressResponseBuilder state(String state) {
        getBillingAddressResponse.setState(state);
        return this;
    }

    public GetBillingAddressResponseBuilder country(String country) {
        getBillingAddressResponse.setCountry(country);
        return this;
    }

    public GetBillingAddressResponseBuilder complement(String complement) {
        getBillingAddressResponse.setComplement(complement);
        return this;
    }

    /**
     * Line 1 for address
     */
    public GetBillingAddressResponseBuilder line1(String line1) {
        getBillingAddressResponse.setLine1(line1);
        return this;
    }

    /**
     * Line 2 for address
     */
    public GetBillingAddressResponseBuilder line2(String line2) {
        getBillingAddressResponse.setLine2(line2);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetBillingAddressResponse build() {
        return getBillingAddressResponse;
    }
}