/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetCheckoutCreditCardPaymentResponseBuilder {
    //the instance to build
    private GetCheckoutCreditCardPaymentResponse getCheckoutCreditCardPaymentResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetCheckoutCreditCardPaymentResponseBuilder() {
        getCheckoutCreditCardPaymentResponse = new GetCheckoutCreditCardPaymentResponse();
    }

    /**
     * Descrição na fatura
     */
    public GetCheckoutCreditCardPaymentResponseBuilder statementDescriptor(String statementDescriptor) {
        getCheckoutCreditCardPaymentResponse.setStatementDescriptor(statementDescriptor);
        return this;
    }

    /**
     * Parcelas
     */
    public GetCheckoutCreditCardPaymentResponseBuilder installments(List<GetCheckoutCardInstallmentOptionsResponse> installments) {
        getCheckoutCreditCardPaymentResponse.setInstallments(installments);
        return this;
    }

    /**
     * Payment Authentication response
     */
    public GetCheckoutCreditCardPaymentResponseBuilder authentication(GetPaymentAuthenticationResponse authentication) {
        getCheckoutCreditCardPaymentResponse.setAuthentication(authentication);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCheckoutCreditCardPaymentResponse build() {
        return getCheckoutCreditCardPaymentResponse;
    }
}