/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class GetCheckoutPixPaymentResponseBuilder {
    //the instance to build
    private GetCheckoutPixPaymentResponse getCheckoutPixPaymentResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetCheckoutPixPaymentResponseBuilder() {
        getCheckoutPixPaymentResponse = new GetCheckoutPixPaymentResponse();
    }

    /**
     * Expires at
     */
    public GetCheckoutPixPaymentResponseBuilder expiresAt(DateTime expiresAt) {
        getCheckoutPixPaymentResponse.setExpiresAt(expiresAt);
        return this;
    }

    /**
     * Additional information
     */
    public GetCheckoutPixPaymentResponseBuilder additionalInformation(List<PixAdditionalInformation> additionalInformation) {
        getCheckoutPixPaymentResponse.setAdditionalInformation(additionalInformation);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCheckoutPixPaymentResponse build() {
        return getCheckoutPixPaymentResponse;
    }
}