/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetCreditCardTransactionResponseBuilder 
        extends GetTransactionResponseBuilder {
    //the instance to build
    private GetCreditCardTransactionResponse getCreditCardTransactionResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetCreditCardTransactionResponseBuilder() {
        getCreditCardTransactionResponse = new GetCreditCardTransactionResponse();
    }

    /**
     * Text that will appear on the credit card's statement
     */
    public GetCreditCardTransactionResponseBuilder statementDescriptor(String statementDescriptor) {
        getCreditCardTransactionResponse.setStatementDescriptor(statementDescriptor);
        return this;
    }

    /**
     * Acquirer name
     */
    public GetCreditCardTransactionResponseBuilder acquirerName(String acquirerName) {
        getCreditCardTransactionResponse.setAcquirerName(acquirerName);
        return this;
    }

    /**
     * Aquirer affiliation code
     */
    public GetCreditCardTransactionResponseBuilder acquirerAffiliationCode(String acquirerAffiliationCode) {
        getCreditCardTransactionResponse.setAcquirerAffiliationCode(acquirerAffiliationCode);
        return this;
    }

    /**
     * Acquirer TID
     */
    public GetCreditCardTransactionResponseBuilder acquirerTid(String acquirerTid) {
        getCreditCardTransactionResponse.setAcquirerTid(acquirerTid);
        return this;
    }

    /**
     * Acquirer NSU
     */
    public GetCreditCardTransactionResponseBuilder acquirerNsu(String acquirerNsu) {
        getCreditCardTransactionResponse.setAcquirerNsu(acquirerNsu);
        return this;
    }

    /**
     * Acquirer authorization code
     */
    public GetCreditCardTransactionResponseBuilder acquirerAuthCode(String acquirerAuthCode) {
        getCreditCardTransactionResponse.setAcquirerAuthCode(acquirerAuthCode);
        return this;
    }

    /**
     * Operation type
     */
    public GetCreditCardTransactionResponseBuilder operationType(String operationType) {
        getCreditCardTransactionResponse.setOperationType(operationType);
        return this;
    }

    /**
     * Card data
     */
    public GetCreditCardTransactionResponseBuilder card(GetCardResponse card) {
        getCreditCardTransactionResponse.setCard(card);
        return this;
    }

    /**
     * Acquirer message
     */
    public GetCreditCardTransactionResponseBuilder acquirerMessage(String acquirerMessage) {
        getCreditCardTransactionResponse.setAcquirerMessage(acquirerMessage);
        return this;
    }

    /**
     * Acquirer Return Code
     */
    public GetCreditCardTransactionResponseBuilder acquirerReturnCode(String acquirerReturnCode) {
        getCreditCardTransactionResponse.setAcquirerReturnCode(acquirerReturnCode);
        return this;
    }

    /**
     * Number of installments
     */
    public GetCreditCardTransactionResponseBuilder installments(Integer installments) {
        getCreditCardTransactionResponse.setInstallments(installments);
        return this;
    }

    /**
     * 3D-S authentication Url
     */
    public GetCreditCardTransactionResponseBuilder threedAuthenticationUrl(String threedAuthenticationUrl) {
        getCreditCardTransactionResponse.setThreedAuthenticationUrl(threedAuthenticationUrl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCreditCardTransactionResponse build() {
        return getCreditCardTransactionResponse;
    }
}