/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetCheckoutBankTransferPaymentResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -24571482987102146L;
    private List<String> bank;
    /** GETTER
     * bank list response
     */
    @JsonGetter("bank")
    public List<String> getBank ( ) { 
        return this.bank;
    }
    
    /** SETTER
     * bank list response
     */
    @JsonSetter("bank")
    public void setBank (List<String> value) { 
        this.bank = value;
    }
 
}
