/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetCheckoutCardInstallmentOptionsResponseBuilder {
    //the instance to build
    private GetCheckoutCardInstallmentOptionsResponse getCheckoutCardInstallmentOptionsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetCheckoutCardInstallmentOptionsResponseBuilder() {
        getCheckoutCardInstallmentOptionsResponse = new GetCheckoutCardInstallmentOptionsResponse();
    }

    /**
     * Número de parcelas
     */
    public GetCheckoutCardInstallmentOptionsResponseBuilder number(String number) {
        getCheckoutCardInstallmentOptionsResponse.setNumber(number);
        return this;
    }

    /**
     * Valor total da compra
     */
    public GetCheckoutCardInstallmentOptionsResponseBuilder total(int total) {
        getCheckoutCardInstallmentOptionsResponse.setTotal(total);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCheckoutCardInstallmentOptionsResponse build() {
        return getCheckoutCardInstallmentOptionsResponse;
    }
}