/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetCheckoutBankTransferPaymentResponseBuilder {
    //the instance to build
    private GetCheckoutBankTransferPaymentResponse getCheckoutBankTransferPaymentResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetCheckoutBankTransferPaymentResponseBuilder() {
        getCheckoutBankTransferPaymentResponse = new GetCheckoutBankTransferPaymentResponse();
    }

    /**
     * bank list response
     */
    public GetCheckoutBankTransferPaymentResponseBuilder bank(List<String> bank) {
        getCheckoutBankTransferPaymentResponse.setBank(bank);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCheckoutBankTransferPaymentResponse build() {
        return getCheckoutBankTransferPaymentResponse;
    }
}