/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetChargesSummaryResponseBuilder {
    //the instance to build
    private GetChargesSummaryResponse getChargesSummaryResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetChargesSummaryResponseBuilder() {
        getChargesSummaryResponse = new GetChargesSummaryResponse();
    }

    public GetChargesSummaryResponseBuilder total(int total) {
        getChargesSummaryResponse.setTotal(total);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetChargesSummaryResponse build() {
        return getChargesSummaryResponse;
    }
}