/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetDeviceResponseBuilder {
    //the instance to build
    private GetDeviceResponse getDeviceResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetDeviceResponseBuilder() {
        getDeviceResponse = new GetDeviceResponse();
    }

    /**
     * Device's platform name
     */
    public GetDeviceResponseBuilder platform(String platform) {
        getDeviceResponse.setPlatform(platform);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetDeviceResponse build() {
        return getDeviceResponse;
    }
}