/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetGatewayRecipientResponseBuilder {
    //the instance to build
    private GetGatewayRecipientResponse getGatewayRecipientResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetGatewayRecipientResponseBuilder() {
        getGatewayRecipientResponse = new GetGatewayRecipientResponse();
    }

    /**
     * Gateway name
     */
    public GetGatewayRecipientResponseBuilder gateway(String gateway) {
        getGatewayRecipientResponse.setGateway(gateway);
        return this;
    }

    /**
     * Status of the recipient on the gateway
     */
    public GetGatewayRecipientResponseBuilder status(String status) {
        getGatewayRecipientResponse.setStatus(status);
        return this;
    }

    /**
     * Recipient id on the gateway
     */
    public GetGatewayRecipientResponseBuilder pgid(String pgid) {
        getGatewayRecipientResponse.setPgid(pgid);
        return this;
    }

    /**
     * Creation date
     */
    public GetGatewayRecipientResponseBuilder createdAt(String createdAt) {
        getGatewayRecipientResponse.setCreatedAt(createdAt);
        return this;
    }

    /**
     * Last update date
     */
    public GetGatewayRecipientResponseBuilder updatedAt(String updatedAt) {
        getGatewayRecipientResponse.setUpdatedAt(updatedAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetGatewayRecipientResponse build() {
        return getGatewayRecipientResponse;
    }
}