/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetInvoiceItemResponseBuilder {
    //the instance to build
    private GetInvoiceItemResponse getInvoiceItemResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetInvoiceItemResponseBuilder() {
        getInvoiceItemResponse = new GetInvoiceItemResponse();
    }

    public GetInvoiceItemResponseBuilder amount(int amount) {
        getInvoiceItemResponse.setAmount(amount);
        return this;
    }

    public GetInvoiceItemResponseBuilder description(String description) {
        getInvoiceItemResponse.setDescription(description);
        return this;
    }

    public GetInvoiceItemResponseBuilder pricingScheme(GetPricingSchemeResponse pricingScheme) {
        getInvoiceItemResponse.setPricingScheme(pricingScheme);
        return this;
    }

    public GetInvoiceItemResponseBuilder priceBracket(GetPriceBracketResponse priceBracket) {
        getInvoiceItemResponse.setPriceBracket(priceBracket);
        return this;
    }

    public GetInvoiceItemResponseBuilder quantity(Integer quantity) {
        getInvoiceItemResponse.setQuantity(quantity);
        return this;
    }

    public GetInvoiceItemResponseBuilder name(String name) {
        getInvoiceItemResponse.setName(name);
        return this;
    }

    /**
     * Subscription Item Id
     */
    public GetInvoiceItemResponseBuilder subscriptionItemId(String subscriptionItemId) {
        getInvoiceItemResponse.setSubscriptionItemId(subscriptionItemId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetInvoiceItemResponse build() {
        return getInvoiceItemResponse;
    }
}