/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class GetPlanResponseBuilder {
    //the instance to build
    private GetPlanResponse getPlanResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetPlanResponseBuilder() {
        getPlanResponse = new GetPlanResponse();
    }

    public GetPlanResponseBuilder id(String id) {
        getPlanResponse.setId(id);
        return this;
    }

    public GetPlanResponseBuilder name(String name) {
        getPlanResponse.setName(name);
        return this;
    }

    public GetPlanResponseBuilder description(String description) {
        getPlanResponse.setDescription(description);
        return this;
    }

    public GetPlanResponseBuilder url(String url) {
        getPlanResponse.setUrl(url);
        return this;
    }

    public GetPlanResponseBuilder statementDescriptor(String statementDescriptor) {
        getPlanResponse.setStatementDescriptor(statementDescriptor);
        return this;
    }

    public GetPlanResponseBuilder interval(String interval) {
        getPlanResponse.setInterval(interval);
        return this;
    }

    public GetPlanResponseBuilder intervalCount(int intervalCount) {
        getPlanResponse.setIntervalCount(intervalCount);
        return this;
    }

    public GetPlanResponseBuilder billingType(String billingType) {
        getPlanResponse.setBillingType(billingType);
        return this;
    }

    public GetPlanResponseBuilder paymentMethods(List<String> paymentMethods) {
        getPlanResponse.setPaymentMethods(paymentMethods);
        return this;
    }

    public GetPlanResponseBuilder installments(List<Integer> installments) {
        getPlanResponse.setInstallments(installments);
        return this;
    }

    public GetPlanResponseBuilder status(String status) {
        getPlanResponse.setStatus(status);
        return this;
    }

    public GetPlanResponseBuilder currency(String currency) {
        getPlanResponse.setCurrency(currency);
        return this;
    }

    public GetPlanResponseBuilder createdAt(DateTime createdAt) {
        getPlanResponse.setCreatedAt(createdAt);
        return this;
    }

    public GetPlanResponseBuilder updatedAt(DateTime updatedAt) {
        getPlanResponse.setUpdatedAt(updatedAt);
        return this;
    }

    public GetPlanResponseBuilder items(List<GetPlanItemResponse> items) {
        getPlanResponse.setItems(items);
        return this;
    }

    public GetPlanResponseBuilder billingDays(List<Integer> billingDays) {
        getPlanResponse.setBillingDays(billingDays);
        return this;
    }

    public GetPlanResponseBuilder shippable(boolean shippable) {
        getPlanResponse.setShippable(shippable);
        return this;
    }

    public GetPlanResponseBuilder metadata(LinkedHashMap<String, String> metadata) {
        getPlanResponse.setMetadata(metadata);
        return this;
    }

    public GetPlanResponseBuilder trialPeriodDays(Integer trialPeriodDays) {
        getPlanResponse.setTrialPeriodDays(trialPeriodDays);
        return this;
    }

    public GetPlanResponseBuilder minimumPrice(Integer minimumPrice) {
        getPlanResponse.setMinimumPrice(minimumPrice);
        return this;
    }

    public GetPlanResponseBuilder deletedAt(DateTime deletedAt) {
        getPlanResponse.setDeletedAt(deletedAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetPlanResponse build() {
        return getPlanResponse;
    }
}