/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetSplitOptionsResponseBuilder {
    //the instance to build
    private GetSplitOptionsResponse getSplitOptionsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetSplitOptionsResponseBuilder() {
        getSplitOptionsResponse = new GetSplitOptionsResponse();
    }

    public GetSplitOptionsResponseBuilder liable(boolean liable) {
        getSplitOptionsResponse.setLiable(liable);
        return this;
    }

    public GetSplitOptionsResponseBuilder chargeProcessingFee(boolean chargeProcessingFee) {
        getSplitOptionsResponse.setChargeProcessingFee(chargeProcessingFee);
        return this;
    }

    public GetSplitOptionsResponseBuilder chargeRemainderFee(String chargeRemainderFee) {
        getSplitOptionsResponse.setChargeRemainderFee(chargeRemainderFee);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetSplitOptionsResponse build() {
        return getSplitOptionsResponse;
    }
}