/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class GetSafetyPayTransactionResponseBuilder 
        extends GetTransactionResponseBuilder {
    //the instance to build
    private GetSafetyPayTransactionResponse getSafetyPayTransactionResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetSafetyPayTransactionResponseBuilder() {
        getSafetyPayTransactionResponse = new GetSafetyPayTransactionResponse();
    }

    /**
     * Payment url
     */
    public GetSafetyPayTransactionResponseBuilder url(String url) {
        getSafetyPayTransactionResponse.setUrl(url);
        return this;
    }

    /**
     * Transaction identifier on bank
     */
    public GetSafetyPayTransactionResponseBuilder bankTid(String bankTid) {
        getSafetyPayTransactionResponse.setBankTid(bankTid);
        return this;
    }

    /**
     * Payment date
     */
    public GetSafetyPayTransactionResponseBuilder paidAt(DateTime paidAt) {
        getSafetyPayTransactionResponse.setPaidAt(paidAt);
        return this;
    }

    /**
     * Paid amount
     */
    public GetSafetyPayTransactionResponseBuilder paidAmount(Integer paidAmount) {
        getSafetyPayTransactionResponse.setPaidAmount(paidAmount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetSafetyPayTransactionResponse build() {
        return getSafetyPayTransactionResponse;
    }
}