/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetTransferTargetResponseBuilder {
    //the instance to build
    private GetTransferTargetResponse getTransferTargetResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetTransferTargetResponseBuilder() {
        getTransferTargetResponse = new GetTransferTargetResponse();
    }

    public GetTransferTargetResponseBuilder targetId(String targetId) {
        getTransferTargetResponse.setTargetId(targetId);
        return this;
    }

    public GetTransferTargetResponseBuilder type(String type) {
        getTransferTargetResponse.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetTransferTargetResponse build() {
        return getTransferTargetResponse;
    }
}