/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class GetTokenResponseBuilder {
    //the instance to build
    private GetTokenResponse getTokenResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetTokenResponseBuilder() {
        getTokenResponse = new GetTokenResponse();
    }

    public GetTokenResponseBuilder id(String id) {
        getTokenResponse.setId(id);
        return this;
    }

    public GetTokenResponseBuilder type(String type) {
        getTokenResponse.setType(type);
        return this;
    }

    public GetTokenResponseBuilder createdAt(DateTime createdAt) {
        getTokenResponse.setCreatedAt(createdAt);
        return this;
    }

    public GetTokenResponseBuilder expiresAt(String expiresAt) {
        getTokenResponse.setExpiresAt(expiresAt);
        return this;
    }

    public GetTokenResponseBuilder card(GetCardTokenResponse card) {
        getTokenResponse.setCard(card);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetTokenResponse build() {
        return getTokenResponse;
    }
}