/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import org.joda.time.DateTime;

public class GetUsageResponseBuilder {
    //the instance to build
    private GetUsageResponse getUsageResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetUsageResponseBuilder() {
        getUsageResponse = new GetUsageResponse();
    }

    /**
     * Id
     */
    public GetUsageResponseBuilder id(String id) {
        getUsageResponse.setId(id);
        return this;
    }

    /**
     * Quantity
     */
    public GetUsageResponseBuilder quantity(int quantity) {
        getUsageResponse.setQuantity(quantity);
        return this;
    }

    /**
     * Description
     */
    public GetUsageResponseBuilder description(String description) {
        getUsageResponse.setDescription(description);
        return this;
    }

    /**
     * Used at
     */
    public GetUsageResponseBuilder usedAt(DateTime usedAt) {
        getUsageResponse.setUsedAt(usedAt);
        return this;
    }

    /**
     * Creation date
     */
    public GetUsageResponseBuilder createdAt(DateTime createdAt) {
        getUsageResponse.setCreatedAt(createdAt);
        return this;
    }

    /**
     * Status
     */
    public GetUsageResponseBuilder status(String status) {
        getUsageResponse.setStatus(status);
        return this;
    }

    public GetUsageResponseBuilder deletedAt(DateTime deletedAt) {
        getUsageResponse.setDeletedAt(deletedAt);
        return this;
    }

    /**
     * Subscription item
     */
    public GetUsageResponseBuilder subscriptionItem(GetSubscriptionItemResponse subscriptionItem) {
        getUsageResponse.setSubscriptionItem(subscriptionItem);
        return this;
    }

    /**
     * Identification code in the client system
     */
    public GetUsageResponseBuilder code(String code) {
        getUsageResponse.setCode(code);
        return this;
    }

    /**
     * Identification group in the client system
     */
    public GetUsageResponseBuilder group(String group) {
        getUsageResponse.setGroup(group);
        return this;
    }

    /**
     * Field used in item scheme type 'Percent'
     */
    public GetUsageResponseBuilder amount(Integer amount) {
        getUsageResponse.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetUsageResponse build() {
        return getUsageResponse;
    }
}