/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class ListChargesResponseBuilder {
    //the instance to build
    private ListChargesResponse listChargesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListChargesResponseBuilder() {
        listChargesResponse = new ListChargesResponse();
    }

    /**
     * The charge objects
     */
    public ListChargesResponseBuilder data(List<GetChargeResponse> data) {
        listChargesResponse.setData(data);
        return this;
    }

    /**
     * Paging object
     */
    public ListChargesResponseBuilder paging(PagingResponse paging) {
        listChargesResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListChargesResponse build() {
        return listChargesResponse;
    }
}