/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class ListCustomersResponseBuilder {
    //the instance to build
    private ListCustomersResponse listCustomersResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListCustomersResponseBuilder() {
        listCustomersResponse = new ListCustomersResponse();
    }

    /**
     * The customer object
     */
    public ListCustomersResponseBuilder data(List<GetCustomerResponse> data) {
        listCustomersResponse.setData(data);
        return this;
    }

    /**
     * Paging object
     */
    public ListCustomersResponseBuilder paging(PagingResponse paging) {
        listCustomersResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListCustomersResponse build() {
        return listCustomersResponse;
    }
}