/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class ListDiscountsResponseBuilder {
    //the instance to build
    private ListDiscountsResponse listDiscountsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListDiscountsResponseBuilder() {
        listDiscountsResponse = new ListDiscountsResponse();
    }

    /**
     * The Discounts response
     */
    public ListDiscountsResponseBuilder data(List<GetDiscountResponse> data) {
        listDiscountsResponse.setData(data);
        return this;
    }

    /**
     * Paging object
     */
    public ListDiscountsResponseBuilder paging(PagingResponse paging) {
        listDiscountsResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListDiscountsResponse build() {
        return listDiscountsResponse;
    }
}