/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class UpdateSubscriptionMinimumPriceRequestBuilder {
    //the instance to build
    private UpdateSubscriptionMinimumPriceRequest updateSubscriptionMinimumPriceRequest;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateSubscriptionMinimumPriceRequestBuilder() {
        updateSubscriptionMinimumPriceRequest = new UpdateSubscriptionMinimumPriceRequest();
    }

    /**
     * Valor mínimo da assinatura
     */
    public UpdateSubscriptionMinimumPriceRequestBuilder minimumPrice(Integer minimumPrice) {
        updateSubscriptionMinimumPriceRequest.setMinimumPrice(minimumPrice);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateSubscriptionMinimumPriceRequest build() {
        return updateSubscriptionMinimumPriceRequest;
    }
}