/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class UpdatePlanRequestBuilder {
    //the instance to build
    private UpdatePlanRequest updatePlanRequest;

    /**
     * Default constructor to initialize the instance
     */
    public UpdatePlanRequestBuilder() {
        updatePlanRequest = new UpdatePlanRequest();
    }

    /**
     * Plan's name
     */
    public UpdatePlanRequestBuilder name(String name) {
        updatePlanRequest.setName(name);
        return this;
    }

    /**
     * Description
     */
    public UpdatePlanRequestBuilder description(String description) {
        updatePlanRequest.setDescription(description);
        return this;
    }

    /**
     * Number os installments
     */
    public UpdatePlanRequestBuilder installments(List<Integer> installments) {
        updatePlanRequest.setInstallments(installments);
        return this;
    }

    /**
     * Text that will be shown on the credit card's statement
     */
    public UpdatePlanRequestBuilder statementDescriptor(String statementDescriptor) {
        updatePlanRequest.setStatementDescriptor(statementDescriptor);
        return this;
    }

    /**
     * Currency
     */
    public UpdatePlanRequestBuilder currency(String currency) {
        updatePlanRequest.setCurrency(currency);
        return this;
    }

    /**
     * Interval
     */
    public UpdatePlanRequestBuilder interval(String interval) {
        updatePlanRequest.setInterval(interval);
        return this;
    }

    /**
     * Interval count
     */
    public UpdatePlanRequestBuilder intervalCount(int intervalCount) {
        updatePlanRequest.setIntervalCount(intervalCount);
        return this;
    }

    /**
     * Payment methods accepted by the plan
     */
    public UpdatePlanRequestBuilder paymentMethods(List<String> paymentMethods) {
        updatePlanRequest.setPaymentMethods(paymentMethods);
        return this;
    }

    /**
     * Billing type
     */
    public UpdatePlanRequestBuilder billingType(String billingType) {
        updatePlanRequest.setBillingType(billingType);
        return this;
    }

    /**
     * Plan status
     */
    public UpdatePlanRequestBuilder status(String status) {
        updatePlanRequest.setStatus(status);
        return this;
    }

    /**
     * Indicates if the plan is shippable
     */
    public UpdatePlanRequestBuilder shippable(boolean shippable) {
        updatePlanRequest.setShippable(shippable);
        return this;
    }

    /**
     * Billing days accepted by the plan
     */
    public UpdatePlanRequestBuilder billingDays(List<Integer> billingDays) {
        updatePlanRequest.setBillingDays(billingDays);
        return this;
    }

    /**
     * Metadata
     */
    public UpdatePlanRequestBuilder metadata(LinkedHashMap<String, String> metadata) {
        updatePlanRequest.setMetadata(metadata);
        return this;
    }

    /**
     * Minimum price
     */
    public UpdatePlanRequestBuilder minimumPrice(Integer minimumPrice) {
        updatePlanRequest.setMinimumPrice(minimumPrice);
        return this;
    }

    /**
     * Number of trial period in days, where the customer will not be charged
     */
    public UpdatePlanRequestBuilder trialPeriodDays(Integer trialPeriodDays) {
        updatePlanRequest.setTrialPeriodDays(trialPeriodDays);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdatePlanRequest build() {
        return updatePlanRequest;
    }
}