/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class UpdatePriceBracketRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -411184899764542446L;
    private int startQuantity;
    private int price;
    private Integer endQuantity;
    private Integer overagePrice;
    /** GETTER
     * Start quantity of the bracket
     */
    @JsonGetter("start_quantity")
    public int getStartQuantity ( ) { 
        return this.startQuantity;
    }
    
    /** SETTER
     * Start quantity of the bracket
     */
    @JsonSetter("start_quantity")
    public void setStartQuantity (int value) { 
        this.startQuantity = value;
    }
 
    /** GETTER
     * Price
     */
    @JsonGetter("price")
    public int getPrice ( ) { 
        return this.price;
    }
    
    /** SETTER
     * Price
     */
    @JsonSetter("price")
    public void setPrice (int value) { 
        this.price = value;
    }
 
    /** GETTER
     * End quantity of the bracket
     */
    @JsonGetter("end_quantity")
    public Integer getEndQuantity ( ) { 
        return this.endQuantity;
    }
    
    /** SETTER
     * End quantity of the bracket
     */
    @JsonSetter("end_quantity")
    public void setEndQuantity (Integer value) { 
        this.endQuantity = value;
    }
 
    /** GETTER
     * Overage price
     */
    @JsonGetter("overage_price")
    public Integer getOveragePrice ( ) { 
        return this.overagePrice;
    }
    
    /** SETTER
     * Overage price
     */
    @JsonSetter("overage_price")
    public void setOveragePrice (Integer value) { 
        this.overagePrice = value;
    }
 
}
