/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class UpdatePricingSchemeRequestBuilder {
    //the instance to build
    private UpdatePricingSchemeRequest updatePricingSchemeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public UpdatePricingSchemeRequestBuilder() {
        updatePricingSchemeRequest = new UpdatePricingSchemeRequest();
    }

    /**
     * Scheme type
     */
    public UpdatePricingSchemeRequestBuilder schemeType(String schemeType) {
        updatePricingSchemeRequest.setSchemeType(schemeType);
        return this;
    }

    /**
     * Price brackets
     */
    public UpdatePricingSchemeRequestBuilder priceBrackets(List<UpdatePriceBracketRequest> priceBrackets) {
        updatePricingSchemeRequest.setPriceBrackets(priceBrackets);
        return this;
    }

    /**
     * Price
     */
    public UpdatePricingSchemeRequestBuilder price(Integer price) {
        updatePricingSchemeRequest.setPrice(price);
        return this;
    }

    /**
     * Minimum price
     */
    public UpdatePricingSchemeRequestBuilder minimumPrice(Integer minimumPrice) {
        updatePricingSchemeRequest.setMinimumPrice(minimumPrice);
        return this;
    }

    /**
     * percentual value used in pricing_scheme Percent
     */
    public UpdatePricingSchemeRequestBuilder percentage(Double percentage) {
        updatePricingSchemeRequest.setPercentage(percentage);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdatePricingSchemeRequest build() {
        return updatePricingSchemeRequest;
    }
}